### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by sterichards** [aotd1/ansible-playbooks#1]
Stephens-MacBook-Pro:yii stephenrichards$ ls
README.md   tasks       yii.yml
Stephens-MacBook-Pro:yii stephenrichards$ ansible-playbook yii.yml -uroot --extra-vars "yii_path=/var/www/yii"
ERROR: Unable to find an inventory file, specify one with -i ?

**Comment by aotd1** [comment]
You need to specify inventory file.
For example if you need to install role locally create somewhere localhost.ini

```
127.0.0.1
```

And use it
`ansible-playbook yii.yml -uroot -ilocalhost.ini -c --extra-vars "yii_path=/var/www/yii"`
`-c` option means run it locally, not via ssh

Also look at [official ansible documentation](http://docs.ansible.com/intro_inventory.html)
